# Generated by Django 4.1.1 on 2022-10-03 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_api', '0003_alter_salesteam_user_alter_supportteam_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageteam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
