# Generated by Django 4.1.1 on 2022-10-03 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0006_alter_client_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 16, 49, 36, 688681)),
        ),
    ]
