# Generated by Django 4.1.1 on 2022-10-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0009_alter_client_created_time_alter_client_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
