# Generated by Django 4.1.1 on 2022-10-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0010_alter_contract_updated_time_alter_event_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
