# Generated by Django 4.1.1 on 2022-10-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0011_alter_contract_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
